const fs = require('fs');
const path = require('path');
const BASE = path.join('C:', 'Users', 'Carlos', 'Desktop', '\u20ac\u20ac', 'E-Nimble', 'Clientela', 'Barefoot', 'inpe');

function write(relPath, lines) {
    const fullPath = path.join(BASE, relPath);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, Array.isArray(lines) ? lines.join('\n') : lines, 'utf8');
    console.log('OK:', relPath);
}

// Header
write('src/components/Header.jsx', [
"'use client';",
"import React, { useState, useEffect } from 'react';",
"import Link from 'next/link';",
"import Image from 'next/image';",
"import { Menu, X, ShoppingBag, Search } from 'lucide-react';",
"",
"const Header = () => {",
"  const [scrolled, setScrolled] = useState(false);",
"  const [isOpen, setIsOpen] = useState(false);",
"  const [isSearchOpen, setIsSearchOpen] = useState(false);",
"  const [searchQuery, setSearchQuery] = useState('');",
"  const searchInputRef = React.useRef(null);",
"",
"  useEffect(() => {",
"    const handleScroll = () => setScrolled(window.scrollY > 20);",
"    window.addEventListener('scroll', handleScroll, { passive: true });",
"    return () => window.removeEventListener('scroll', handleScroll);",
"  }, []);",
"",
"  return (",
"    <header style={{ position: 'fixed', top: '20px', left: 0, width: '100%', zIndex: 100, padding: '0 2rem', display: 'flex', justifyContent: 'center', transition: 'transform 0.3s ease-in-out' }}>",
"      <div style={{ backgroundColor: 'white', borderRadius: '9999px', padding: '12px 32px', width: '100%', maxWidth: '1100px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', boxShadow: scrolled ? '0 4px 20px rgba(0,0,0,0.05)' : 'none', transition: 'all 0.3s ease' }}>",
"        <Link href='/' style={{ display: 'flex', alignItems: 'center' }}>",
"          <img src='/logo.png' alt='Inpe Logo' style={{ height: '45px', width: 'auto' }} />",
"        </Link>",
"        <nav className='desktop-nav' style={{ display: 'flex', gap: '24px', fontWeight: 'bold', fontSize: '0.9rem', color: '#555', textTransform: 'uppercase' }}>",
"          <Link href='/' className='nav-item'>In\u00edcio</Link>",
"          <Link href='/loja' className='nav-item'>Loja</Link>",
"          <Link href='/historia' className='nav-item'>Nossa Hist\u00f3ria</Link>",
"          <Link href='/contactos' className='nav-item'>Contactos</Link>",
"        </nav>",
"        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>",
"          <div style={{ display: 'flex', alignItems: 'center', backgroundColor: isSearchOpen ? 'var(--color-background)' : 'transparent', borderRadius: '50px', padding: isSearchOpen ? '4px 8px' : '0', transition: 'all 0.3s ease', border: isSearchOpen ? '1px solid #eee' : '1px solid transparent' }}>",
"            <button onClick={() => { setIsSearchOpen(!isSearchOpen); if (!isSearchOpen) setTimeout(() => searchInputRef.current?.focus(), 100); }} style={{ background: 'none', border: 'none', color: isSearchOpen ? 'var(--color-primary)' : '#555', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', padding: '8px', borderRadius: '50%' }}>",
"              <Search size={20} />",
"            </button>",
"            <input ref={searchInputRef} type='text' placeholder='Pesquisar...' value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} onKeyDown={(e) => { if (e.key === 'Escape') setIsSearchOpen(false); }} onBlur={() => { if (searchQuery.trim() === '') setIsSearchOpen(false); }} style={{ width: isSearchOpen ? '150px' : '0px', opacity: isSearchOpen ? 1 : 0, border: 'none', background: 'transparent', outline: 'none', padding: isSearchOpen ? '0 8px 0 4px' : '0', transition: 'width 0.3s, opacity 0.2s, padding 0.3s', color: 'var(--color-text)', fontSize: '0.9rem' }} />",
"          </div>",
"          <button style={{ background: 'var(--color-primary)', color: 'white', width: '40px', height: '40px', borderRadius: '50%', border: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}>",
"            <ShoppingBag size={20} />",
"          </button>",
"          <button onClick={() => setIsOpen(!isOpen)} className='mobile-toggle' style={{ display: 'none', background: 'none', border: 'none', cursor: 'pointer' }}>",
"            {isOpen ? <X /> : <Menu />}",
"          </button>",
"        </div>",
"      </div>",
"      {isOpen && (",
"        <div style={{ position: 'absolute', top: '80px', left: '2rem', right: '2rem', backgroundColor: 'white', borderRadius: '20px', padding: '2rem', boxShadow: '0 10px 40px rgba(0,0,0,0.1)', display: 'flex', flexDirection: 'column', gap: '1rem', textAlign: 'center' }}>",
"          <Link href='/' onClick={() => setIsOpen(false)}>In\u00edcio</Link>",
"          <Link href='/loja' onClick={() => setIsOpen(false)}>Loja</Link>",
"          <Link href='/historia' onClick={() => setIsOpen(false)}>Nossa Hist\u00f3ria</Link>",
"          <Link href='/contactos' onClick={() => setIsOpen(false)}>Contactos</Link>",
"        </div>",
"      )}",
"    </header>",
"  );",
"};",
"",
"export default Header;",
]);

// Footer
write('src/components/Footer.jsx', [
"'use client';",
"import React from 'react';",
"import Link from 'next/link';",
"import { Facebook, Instagram } from 'lucide-react';",
"",
"const Footer = () => {",
"  return (",
"    <footer style={{ backgroundColor: 'var(--color-footer-yellow)', padding: '4rem 2rem 1rem' }}>",
"      <div style={{ maxWidth: '1200px', margin: '0 auto', display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '4rem', marginBottom: '4rem' }}>",
"        <div style={{ flex: '1 1 300px' }}>",
"          <img src='/logo.png' alt='Inpe Logo' style={{ height: '60px', width: 'auto', marginBottom: '1rem' }} />",
"          <p style={{ fontWeight: 'bold', fontSize: '0.9rem', maxWidth: '300px', lineHeight: 1.6 }}>",
"            Criando os cal\u00e7ados mais macios e m\u00e1gicos para os pequenos aventureiros de amanh\u00e3. \u00c9ticos, sustent\u00e1veis e repletos de alegria.",
"          </p>",
"          <div style={{ display: 'flex', gap: '1rem', marginTop: '2rem' }}>",
"            <a href='#' style={{ width: '40px', height: '40px', background: 'var(--color-teal)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff' }}><Facebook size={20} strokeWidth={2.5} /></a>",
"            <a href='#' style={{ width: '40px', height: '40px', background: 'var(--color-teal)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff' }}><Instagram size={20} strokeWidth={2.5} /></a>",
"          </div>",
"        </div>",
"        <div style={{ display: 'flex', gap: '4rem', flexWrap: 'wrap' }}>",
"          <div>",
"            <h3 style={{ fontSize: '1.2rem', fontWeight: '900', marginBottom: '1.5rem', color: '#333' }}>Loja</h3>",
"            <ul style={{ display: 'flex', flexDirection: 'column', gap: '10px', fontWeight: 'bold', fontSize: '0.9rem' }}>",
"              <li><Link href='#'>Mais Vendidos</Link></li>",
"              <li><Link href='#'>Nova Cole\u00e7\u00e3o</Link></li>",
"              <li><Link href='#'>Crian\u00e7as</Link></li>",
"              <li><Link href='#'>Adultos</Link></li>",
"            </ul>",
"          </div>",
"          <div>",
"            <h3 style={{ fontSize: '1.2rem', fontWeight: '900', marginBottom: '1.5rem', color: '#333' }}>Ajuda</h3>",
"            <ul style={{ display: 'flex', flexDirection: 'column', gap: '10px', fontWeight: 'bold', fontSize: '0.9rem' }}>",
"              <li><Link href='#'>Guia de Tamanhos</Link></li>",
"              <li><Link href='#'>Envios e Devolu\u00e7\u00f5es</Link></li>",
"              <li><Link href='#'>Contactos</Link></li>",
"            </ul>",
"          </div>",
"        </div>",
"      </div>",
"      <div style={{ borderTop: '2px solid rgba(0,0,0,0.05)', paddingTop: '1rem', display: 'flex', justifyContent: 'space-between', flexWrap: 'wrap', fontSize: '0.8rem', fontWeight: 'bold', color: '#444' }}>",
"        <span>\u00a9 2024 Little Steps Footwear. All rights reserved.</span>",
"        <span>Feito com amor por <span style={{ color: 'var(--color-teal)' }}>E-Nimble</span></span>",
"      </div>",
"    </footer>",
"  );",
"};",
"export default Footer;",
]);

// Layout
write('src/components/Layout.jsx', [
"import React from 'react';",
"import Header from './Header';",
"import Footer from './Footer';",
"",
"const Layout = ({ children }) => (",
"  <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>",
"    <Header />",
"    <main style={{ flex: 1, paddingTop: '80px' }}>{children}</main>",
"    <Footer />",
"  </div>",
");",
"",
"export default Layout;",
]);

// ProductCard
write('src/components/ProductCard.jsx', [
"'use client';",
"import React from 'react';",
"import { motion } from 'framer-motion';",
"",
"const ProductCard = ({ title, price, image, category, id, compact = false }) => (",
"  <motion.div",
"    whileHover={{ y: compact ? -4 : -8 }}",
"    style={{ backgroundColor: 'white', borderRadius: compact ? '16px' : '24px', padding: compact ? '12px' : '20px', position: 'relative', boxShadow: 'var(--shadow-card)', display: 'flex', flexDirection: 'column', color: 'inherit', height: '100%', minHeight: compact ? '260px' : '340px' }}",
"  >",
"    <div style={{ height: compact ? '120px' : '180px', backgroundColor: 'white', borderRadius: compact ? '12px' : '16px', marginBottom: compact ? '10px' : '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>",
"      <img src={image} alt={title} style={{ width: '100%', height: '100%', objectFit: 'contain', padding: '8px' }} />",
"    </div>",
"    <h3 style={{ fontSize: compact ? '1rem' : '1.25rem', fontWeight: '800', color: '#1f2937', marginBottom: '4px', lineHeight: '1.2' }}>{title}</h3>",
"    <p style={{ fontSize: compact ? '0.75rem' : '0.85rem', color: '#9ca3af', marginBottom: compact ? '10px' : '16px', lineHeight: '1.4' }}>Conforto e liberdade para os teus p\u00e9s</p>",
"    <div style={{ marginTop: 'auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>",
"      <span style={{ fontSize: compact ? '1.2rem' : '1.5rem', fontWeight: 'bold', color: '#854931' }}>\u20ac{price}</span>",
"      <button style={{ width: compact ? '36px' : '52px', height: compact ? '36px' : '52px', borderRadius: '50%', backgroundColor: '#f7c969', border: 'none', color: '#854931', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', fontSize: compact ? '1.25rem' : '1.75rem', transition: 'transform 0.2s' }}>+</button>",
"    </div>",
"  </motion.div>",
");",
"",
"export default ProductCard;",
]);

// ModelViewer Client
write('src/components/ModelViewer.jsx', [
"'use client';",
"import React, { Suspense, useRef } from 'react';",
"import { Canvas, useFrame } from '@react-three/fiber';",
"import { OrbitControls, useGLTF, Stage } from '@react-three/drei';",
"",
"function Model({ url }) {",
"  const { scene } = useGLTF(url);",
"  const ref = useRef();",
"  useFrame(() => { if (ref.current) ref.current.rotation.y = window.scrollY * 0.005; });",
"  return <primitive ref={ref} object={scene} />;",
"}",
"",
"export default function ModelViewer({ modelPath, autoRotate = false }) {",
"  return (",
"    <div style={{ width: '100%', height: '100%', minHeight: '300px' }}>",
"      <Canvas shadows dpr={[1, 2]} camera={{ fov: 50 }}>",
"        <Suspense fallback={null}>",
"          <Stage environment='city' intensity={0.6}>",
"            <Model url={modelPath} />",
"          </Stage>",
"        </Suspense>",
"        <OrbitControls autoRotate={autoRotate} enableZoom={false} />",
"      </Canvas>",
"    </div>",
"  );",
"}",
]);

// FilterSidebar
write('src/components/FilterSidebar.jsx', [
"'use client';",
"import React from 'react';",
"",
"const FilterSidebar = ({ filters, setFilters }) => {",
"  const toggleCategory = (e) => {",
"    const { value, checked } = e.target;",
"    const cur = filters.categories || [];",
"    setFilters({ ...filters, categories: checked ? [...cur, value] : cur.filter(c => c !== value) });",
"  };",
"  const toggleSub = (e) => {",
"    const { value, checked } = e.target;",
"    const cur = filters.subcategories || [];",
"    setFilters({ ...filters, subcategories: checked ? [...cur, value] : cur.filter(c => c !== value) });",
"  };",
"  const toggleSize = (size) => {",
"    const cur = filters.sizes || [];",
"    setFilters({ ...filters, sizes: cur.includes(size) ? cur.filter(s => s !== size) : [...cur, size] });",
"  };",
"",
"  return (",
"    <div style={{ width: '100%', maxWidth: '300px', height: 'fit-content' }}>",
"      <div style={{ backgroundColor: '#fff', borderRadius: '20px', padding: '2rem', boxShadow: '0 10px 30px rgba(0,0,0,0.05)', border: '1px solid #f0f0f0' }}>",
"        <h3 style={{ fontSize: '1.5rem', marginBottom: '2rem', color: '#333', marginTop: 0 }}>Filtros</h3>",
"        <div style={{ marginBottom: '2.5rem' }}>",
"          <h4 style={{ fontSize: '1.1rem', marginBottom: '1rem', color: '#555' }}>Pre\u00e7o</h4>",
"          <div style={{ position: 'relative', height: '40px', width: '100%' }}>",
"            <div style={{ position: 'absolute', width: '100%', height: '6px', backgroundColor: '#eee', borderRadius: '99px', top: '50%', transform: 'translateY(-50%)', left: 0 }}></div>",
"            <div style={{ position: 'absolute', height: '6px', backgroundColor: 'var(--color-teal)', borderRadius: '99px', left: ((filters.price.min / 200) * 100) + '%', right: (100 - (filters.price.max / 200) * 100) + '%', top: '50%', transform: 'translateY(-50%)', zIndex: 2 }}></div>",
"            <input type='range' min='0' max='200' value={filters.price.min} onChange={(e) => { const val = Math.min(Number(e.target.value), filters.price.max - 1); setFilters({ ...filters, price: { ...filters.price, min: val } }); }} className='thumb thumb-left' style={{ zIndex: filters.price.min > 180 ? 5 : 3, position: 'absolute', width: '100%', top: '50%', transform: 'translateY(-50%)', margin: 0, left: 0 }} />",
"            <input type='range' min='0' max='200' value={filters.price.max} onChange={(e) => { const val = Math.max(Number(e.target.value), filters.price.min + 1); setFilters({ ...filters, price: { ...filters.price, max: val } }); }} className='thumb thumb-right' style={{ zIndex: 4, position: 'absolute', width: '100%', top: '50%', transform: 'translateY(-50%)', margin: 0, left: 0 }} />",
"          </div>",
"          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '0.5rem' }}>",
"            <div style={{ border: '1px solid #ddd', padding: '4px 12px', borderRadius: '20px', fontSize: '0.9rem', color: '#666', background: '#f9f9f9' }}>{filters.price.min}\u20ac</div>",
"            <div style={{ border: '1px solid #ddd', padding: '4px 12px', borderRadius: '20px', fontSize: '0.9rem', color: '#666', background: '#f9f9f9' }}>{filters.price.max}\u20ac</div>",
"          </div>",
"        </div>",
"        <div style={{ marginBottom: '2.5rem' }}>",
"          <h4 style={{ fontSize: '1.1rem', marginBottom: '1rem', color: '#555' }}>G\u00eanero</h4>",
"          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>",
"            {['homem', 'mulher', 'crianca'].map(cat => (",
"              <label key={cat} style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', color: '#666', fontSize: '1rem' }}>",
"                <input type='checkbox' value={cat} checked={filters.categories?.includes(cat)} onChange={toggleCategory} style={{ accentColor: 'var(--color-teal)', width: '18px', height: '18px' }} />",
"                <span style={{ textTransform: 'capitalize' }}>{cat === 'crianca' ? 'Crian\u00e7a' : cat}</span>",
"              </label>",
"            ))}",
"          </div>",
"        </div>",
"        <div style={{ marginBottom: '2.5rem' }}>",
"          <h4 style={{ fontSize: '1.1rem', marginBottom: '1rem', color: '#555' }}>Estilo</h4>",
"          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>",
"            {['Botas', 'Desportivo', 'Lonas', 'Sand\u00e1lias'].map(sc => (",
"              <label key={sc} style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', color: '#666', fontSize: '1rem' }}>",
"                <input type='checkbox' value={sc} checked={filters.subcategories?.includes(sc)} onChange={toggleSub} style={{ accentColor: 'var(--color-teal)', width: '18px', height: '18px' }} />",
"                <span>{sc}</span>",
"              </label>",
"            ))}",
"          </div>",
"        </div>",
"        <div style={{ marginBottom: '2.5rem' }}>",
"          <h4 style={{ fontSize: '1.1rem', marginBottom: '1rem', color: '#555' }}>Tamanho</h4>",
"          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>",
"            {['crian\u00e7a', 'adulto'].map(s => (",
"              <label key={s} style={{ display: 'flex', alignItems: 'center', gap: '10px', cursor: 'pointer', color: '#666', fontSize: '1rem' }}>",
"                <input type='checkbox' value={s} checked={filters.sizes?.includes(s)} onChange={(e) => toggleSize(e.target.value)} style={{ accentColor: 'var(--color-teal)', width: '18px', height: '18px' }} />",
"                <span style={{ textTransform: 'capitalize' }}>{s}</span>",
"              </label>",
"            ))}",
"          </div>",
"        </div>",
"      </div>",
"    </div>",
"  );",
"};",
"export default FilterSidebar;",
]);

console.log('Components created!');
